export type Zikr = {
    id: number;
    arabic: string;
    transliteration: string;
    translation: string;
    bengaliMeaning: string;
    virtue: string;
    target: number;
    category: "সাধারণ জিকির" | "সকাল-সন্ধ্যার জিকির" | "মাসনূন জিকির";
};

export const zikrList: Zikr[] = [
    {
        id: 1,
        arabic: "سُبْحَانَ ٱللَّٰهِ",
        transliteration: "SubhanAllah",
        translation: "Glory be to Allah",
        bengaliMeaning: "আল্লাহ পবিত্র",
        virtue: "যে ব্যক্তি ১০০ বার 'সুবহানাল্লাহ' পাঠ করবে, তার জন্য ১০০০ নেকি লেখা হবে এবং ১০০০ গুনাহ মুছে ফেলা হবে। (সহিহ মুসলিম)",
        target: 33,
        category: "সাধারণ জিকির",
    },
    {
        id: 2,
        arabic: "ٱلْحَمْدُ لِلَّٰهِ",
        transliteration: "Alhamdulillah",
        translation: "Praise be to Allah",
        bengaliMeaning: "সমস্ত প্রশংসা আল্লাহর",
        virtue: "'আলহামদুলিল্লাহ' весов (মিজান) পূর্ণ করে দেয় এবং 'সুবহানাল্লাহ' ও 'আলহামদুলিল্লাহ' আসমান ও জমিনের মধ্যবর্তী স্থান পূর্ণ করে দেয়। (সহিহ মুসলিম)",
        target: 33,
        category: "সাধারণ জিকির",
    },
    {
        id: 3,
        arabic: "ٱللَّٰهُ أَكْبَرُ",
        transliteration: "Allahu Akbar",
        translation: "Allah is the Greatest",
        bengaliMeaning: "আল্লাহ সর্বশ্রেষ্ঠ",
        virtue: "আল্লাহর কাছে সবচেয়ে প্রিয় চারটি বাক্য হলো: সুবহানাল্লাহ, আলহামদুলিল্লাহ, লা ইলাহা ইল্লাল্লাহ এবং আল্লাহু আকবার। (সহিহ মুসলিম)",
        target: 34,
        category: "সাধারণ জিকির",
    },
    {
        id: 4,
        arabic: "لَا إِلَٰهَ إِلَّا ٱللَّٰهُ",
        transliteration: "La ilaha illallah",
        translation: "There is no god but Allah",
        bengaliMeaning: "আল্লাহ ছাড়া কোন ইলাহ নেই",
        virtue: "সর্বশ্রেষ্ঠ জিকির হলো 'লা ইলাহা ইল্লাল্লাহ' এবং সর্বশ্রেষ্ঠ দোয়া হলো 'আলহামদুলিল্লাহ'।" ,
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 5,
        arabic: "أَسْتَغْفِرُ ٱللَّٰهَ",
        transliteration: "Astaghfirullah",
        translation: "I seek forgiveness from Allah",
        bengaliMeaning: "আমি আল্লাহর কাছে ক্ষমা চাই",
        virtue: "যে ব্যক্তি নিয়মিত ইস্তেগফার করে, আল্লাহ তাকে সকল সংকট থেকে উত্তরণের পথ বের করে দেন এবং সকল দুশ্চিন্তা থেকে মুক্তি দেন।",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 13,
        arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِٱللَّٰهِ",
        transliteration: "La hawla wa la quwwata illa billah",
        translation: "There is no might or power except with Allah",
        bengaliMeaning: "আল্লাহর সাহায্য ছাড়া পাপ থেকে বিরত থাকা এবং সৎকাজ করা সম্ভব নয়",
        virtue: "রাসূলুল্লাহ (সা.) বলেছেন, 'লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ' জান্নাতের গুপ্তধনগুলোর মধ্যে একটি। এটি দুশ্চিন্তা ও বিপদ থেকে মুক্তির উপায়।",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 14,
        arabic: "حَسْبُنَا ٱللَّٰهُ وَنِعْمَ ٱلْوَكِيلُ",
        transliteration: "Hasbunallahu wa ni'mal wakeel",
        translation: "Allah is sufficient for us, and He is the best Disposer of affairs",
        bengaliMeaning: "আল্লাহই আমাদের জন্য যথেষ্ট এবং তিনি উত্তম কর্মবিধায়ক",
        virtue: "ইব্রাহিম (আ.)-কে যখন আগুনে নিক্ষেপ করা হয়েছিল, তখন তিনি এই দোয়া পাঠ করেছিলেন। কঠিন বিপদে আল্লাহর ওপর পূর্ণ আস্থা রাখার জন্য এটি একটি শক্তিশালী দোয়া।",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 15,
        arabic: "ٱللَّٰهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ",
        transliteration: "Allahumma salli 'ala Muhammad",
        translation: "O Allah, send blessings upon Muhammad",
        bengaliMeaning: "হে আল্লাহ! মুহাম্মদের উপর রহমত বর্ষণ করুন",
        virtue: "যে ব্যক্তি আমার উপর একবার দরুদ পাঠ করবে, আল্লাহ তার উপর দশবার রহমত বর্ষণ করবেন, তার দশটি গুনাহ মাফ করবেন এবং তার দশটি মর্যাদা বৃদ্ধি করবেন। (সুনানে নাসায়ী)",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 16,
        arabic: "ٱللَّٰهُمَّ ٱغْفِرْ لِي",
        transliteration: "Allahummaghfirli",
        translation: "O Allah, forgive me",
        bengaliMeaning: "হে আল্লাহ! আমাকে ক্ষমা করুন",
        virtue: "ক্ষমা প্রার্থনার মাধ্যমে আল্লাহর নৈকট্য লাভ করা যায়। রাসূল (সা.) প্রতিদিন ৭০ বারের বেশি আল্লাহর কাছে ক্ষমা চাইতেন। এই দোয়াটি নিজের গুনাহের জন্য অনুশোচনার একটি সহজ উপায়।",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 6,
        arabic: "آيَةُ الْكُرْسِيِّ",
        transliteration: "Ayatul Kursi",
        translation: "The Verse of the Throne",
        bengaliMeaning: "আয়াতুল কুরসি",
        virtue: "যে ব্যক্তি প্রতি ফরয নামাজের পর আয়াতুল কুরসি পাঠ করবে, তার এবং জান্নাতের মধ্যে কেবল মৃত্যুই বাধা থাকবে। (সুনানে নাসায়ী)",
        target: 1,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 7,
        arabic: "سُورَةُ الْإِخْلَاصِ",
        transliteration: "Surah Al-Ikhlas",
        translation: "The Sincerity",
        bengaliMeaning: "সূরা ইখলাস",
        virtue: "রাসূল (সা.) বলেছেন, 'সূরা ইখলাস কুরআনের এক-তৃতীয়াংশের সমান।' সকাল ও সন্ধ্যায় তিনবার পাঠ করলে তা সকল বিপদ থেকে রক্ষা করে।",
        target: 3,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 8,
        arabic: "سُورَةُ الْفَلَقِ",
        transliteration: "Surah Al-Falaq",
        translation: "The Daybreak",
        bengaliMeaning: "সূরা ফালাক",
        virtue: "সকাল ও সন্ধ্যায় তিনবার সূরা ফালাক পাঠ করলে যাবতীয় অনিষ্ট ও জাদু থেকে আল্লাহর আশ্রয় লাভ হয়।",
        target: 3,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 9,
        arabic: "سُورَةُ النَّاسِ",
        transliteration: "Surah An-Nas",
        translation: "The Mankind",
        bengaliMeaning: "সূরা নাস",
        virtue: "সকাল ও সন্ধ্যায় তিনবার সূরা নাস পাঠ করলে শয়তানের কুমন্ত্রণা ও মানুষের অনিষ্ট থেকে সুরক্ষা পাওয়া যায়।",
        target: 3,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 17,
        arabic: "لَا إِلَٰهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيْكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيْرٌ",
        transliteration: "La ilaha illallahu wahdahu la sharika lahu, lahul-mulku wa lahul-hamdu, wa huwa 'ala kulli shay'in qadir",
        translation: "There is no god but Allah alone, with no partner or associate, His is the dominion and to Him is praise, and He has power over all things.",
        bengaliMeaning: "আল্লাহ ছাড়া কোনো উপাস্য নেই, তিনি এক, তাঁর কোনো অংশীদার নেই। রাজত্ব তাঁরই এবং প্রশংসা তাঁরই। তিনি সবকিছুর উপর ক্ষমতাবান।",
        virtue: "যে ব্যক্তি এই দোয়াটি দিনে ১০০ বার পাঠ করবে, সে দশজন দাস মুক্ত করার সমান সওয়াব পাবে, তার জন্য ১০০টি নেকি লেখা হবে, তার ১০০টি গুনাহ মাফ করা হবে এবং সে শয়তান থেকে সুরক্ষিত থাকবে। (সহিহ বুখারি)",
        target: 100,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 18,
        arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
        transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'alim",
        translation: "In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, the All-Knowing.",
        bengaliMeaning: "আল্লাহর নামে, যাঁর নামের সাথে আসমান ও জমিনের কোনো কিছুই ক্ষতি করতে পারে না। আর তিনি সর্বশ্রোতা, সর্বজ্ঞ।",
        virtue: "যে ব্যক্তি সকালে ও সন্ধ্যায় এই দোয়াটি তিনবার পাঠ করবে, কোনো কিছুই তার ক্ষতি করতে পারবে না। (সুনানে তিরমিজি)",
        target: 3,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 19,
        arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
        transliteration: "Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alay, wa abu'u laka bidhanbi faghfir li, fa'innahu la yaghfirudh-dhunuba illa ant.",
        translation: "O Allah, You are my Lord, there is no god but You. You created me and I am Your slave. I am upon Your covenant and Your promise as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me, and I acknowledge my sin, so forgive me, for none forgives sins except You.",
        bengaliMeaning: "হে আল্লাহ! আপনি আমার প্রতিপালক, আপনি ছাড়া কোনো উপাস্য নেই। আপনি আমাকে সৃষ্টি করেছেন এবং আমি আপনার বান্দা। আমি আমার সাধ্যমতো আপনার সাথে কৃত প্রতিজ্ঞা ও অঙ্গীকারের উপর আছি। আমি যা করেছি, তার অনিষ্ট থেকে আপনার আশ্রয় চাই। আমার উপর আপনার প্রদত্ত নিয়ামতের কথা আমি স্বীকার করছি এবং আমার পাপের কথাও স্বীকার করছি। অতএব, আপনি আমাকে ক্ষমা করে দিন। নিশ্চয়ই আপনি ছাড়া পাপ ক্ষমা করার কেউ নেই।",
        virtue: "এটি 'সাইয়্যিদুল ইস্তিগফার' বা ক্ষমা প্রার্থনার শ্রেষ্ঠ দোয়া। যে ব্যক্তি সকালে এ দোয়াটি পাঠ করবে এবং সন্ধ্যার আগে মারা যাবে, সে জান্নাতি হবে। আর যে ব্যক্তি সন্ধ্যায় পাঠ করবে এবং সকালের আগে মারা যাবে, সেও জান্নাতি হবে। (সহিহ বুখারি)",
        target: 1,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 10,
        arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
        transliteration: "Bismika Allahumma amutu wa ahya",
        translation: "In Your name, O Allah, I die and I live",
        bengaliMeaning: "হে আল্লাহ! আপনার নামেই আমি মৃত্যুবরণ করি এবং জীবিত হই",
        virtue: "রাসূলুল্লাহ (সা.) ঘুমানোর সময় এই দোয়াটি পড়তেন। এটি আল্লাহর হাতে নিজের জীবন ও মৃত্যু সঁপে দেওয়ার প্রতীক। (সহিহ বুখারি)",
        target: 1,
        category: "মাসনূন জিকির",
    },
    {
        id: 11,
        arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
        transliteration: "Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana Muslimin",
        translation: "Praise is to Allah Who has fed us and given us drink, and made us Muslims",
        bengaliMeaning: "সমস্ত প্রশংসা আল্লাহর জন্য, যিনি আমাদের খাইয়েছেন, পান করিয়েছেন এবং মুসলিমদের অন্তর্ভুক্ত করেছেন",
        virtue: "খাওয়ার পর এই দোয়া পাঠ করলে আল্লাহর প্রতি কৃতজ্ঞতা প্রকাশ করা হয় এবং তিনি নিয়ামত বাড়িয়ে দেন।",
        target: 1,
        category: "মাসনূন জিকির",
    },
    {
        id: 12,
        arabic: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ",
        transliteration: "Bismillahi, tawakkaltu 'alallah, la hawla wa la quwwata illa billah",
        translation: "In the name of Allah, I trust in Allah; there is no might and no power but in Allah",
        bengaliMeaning: "আল্লাহর নামে, আল্লাহর উপর ভরসা করলাম, আল্লাহ ছাড়া কোনো শক্তি বা ক্ষমতা নেই",
        virtue: "ঘর থেকে বের হওয়ার সময় এই দোয়া পাঠ করলে শয়তান থেকে সুরক্ষা পাওয়া যায় এবং আল্লাহ তার জন্য যথেষ্ট হয়ে যান। (সুনানে আবু দাউদ)",
        target: 1,
        category: "মাসনূন জিকির",
    }
];
