export type Zikr = {
    id: number;
    arabic: string;
    transliteration: string;
    translation: string;
    bengaliMeaning: string;
    virtue: string;
    target: number;
    category: "সাধারণ জিকির" | "সকাল-সন্ধ্যার জিকির" | "মাসনূন জিকির";
};

export const zikrList: Zikr[] = [
    {
        id: 1,
        arabic: "سُبْحَانَ ٱللَّٰهِ",
        transliteration: "SubhanAllah",
        translation: "Glory be to Allah",
        bengaliMeaning: "আল্লাহ পবিত্র",
        virtue: "যে ব্যক্তি ১০০ বার 'সুবহানাল্লাহ' পাঠ করবে, তার জন্য ১০০০ নেকি লেখা হবে এবং ১০০০ গুনাহ মুছে ফেলা হবে। (সহিহ মুসলিম)",
        target: 33,
        category: "সাধারণ জিকির",
    },
    {
        id: 2,
        arabic: "ٱلْحَمْدُ لِلَّٰهِ",
        transliteration: "Alhamdulillah",
        translation: "Praise be to Allah",
        bengaliMeaning: "সমস্ত প্রশংসা আল্লাহর",
        virtue: "'আলহামদুলিল্লাহ' весов (মিজান) পূর্ণ করে দেয় এবং 'সুবহানাল্লাহ' ও 'আলহামদুলিল্লাহ' আসমান ও জমিনের মধ্যবর্তী স্থান পূর্ণ করে দেয়। (সহিহ মুসলিম)",
        target: 33,
        category: "সাধারণ জিকির",
    },
    {
        id: 3,
        arabic: "ٱللَّٰهُ أَكْبَرُ",
        transliteration: "Allahu Akbar",
        translation: "Allah is the Greatest",
        bengaliMeaning: "আল্লাহ সর্বশ্রেষ্ঠ",
        virtue: "আল্লাহর কাছে সবচেয়ে প্রিয় চারটি বাক্য হলো: সুবহানাল্লাহ, আলহামদুলিল্লাহ, লা ইলাহা ইল্লাল্লাহ এবং আল্লাহু আকবার। (সহিহ মুসলিম)",
        target: 34,
        category: "সাধারণ জিকির",
    },
    {
        id: 4,
        arabic: "لَا إِلَٰهَ إِلَّا ٱللَّٰهُ",
        transliteration: "La ilaha illallah",
        translation: "There is no god but Allah",
        bengaliMeaning: "আল্লাহ ছাড়া কোন ইলাহ নেই",
        virtue: "সর্বশ্রেষ্ঠ জিকির হলো 'লা ইলাহা ইল্লাল্লাহ' এবং সর্বশ্রেষ্ঠ দোয়া হলো 'আলহামদুলিল্লাহ'।" ,
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 5,
        arabic: "أَسْتَغْفِرُ ٱللَّٰهَ",
        transliteration: "Astaghfirullah",
        translation: "I seek forgiveness from Allah",
        bengaliMeaning: "আমি আল্লাহর কাছে ক্ষমা চাই",
        virtue: "যে ব্যক্তি নিয়মিত ইস্তেগফার করে, আল্লাহ তাকে সকল সংকট থেকে উত্তরণের পথ বের করে দেন এবং সকল দুশ্চিন্তা থেকে মুক্তি দেন।",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 13,
        arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِٱللَّٰهِ",
        transliteration: "La hawla wa la quwwata illa billah",
        translation: "There is no might or power except with Allah",
        bengaliMeaning: "আল্লাহর সাহায্য ছাড়া পাপ থেকে বিরত থাকা এবং সৎকাজ করা সম্ভব নয়",
        virtue: "রাসূলুল্লাহ (সা.) বলেছেন, 'লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ' জান্নাতের গুপ্তধনগুলোর মধ্যে একটি। এটি দুশ্চিন্তা ও বিপদ থেকে মুক্তির উপায়।",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 14,
        arabic: "حَسْبُنَا ٱللَّٰهُ وَنِعْمَ ٱلْوَكِيلُ",
        transliteration: "Hasbunallahu wa ni'mal wakeel",
        translation: "Allah is sufficient for us, and He is the best Disposer of affairs",
        bengaliMeaning: "আল্লাহই আমাদের জন্য যথেষ্ট এবং তিনি উত্তম কর্মবিধায়ক",
        virtue: "ইব্রাহিম (আ.)-কে যখন আগুনে নিক্ষেপ করা হয়েছিল, তখন তিনি এই দোয়া পাঠ করেছিলেন। কঠিন বিপদে আল্লাহর ওপর পূর্ণ আস্থা রাখার জন্য এটি একটি শক্তিশালী দোয়া।",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 15,
        arabic: "ٱللَّٰهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ",
        transliteration: "Allahumma salli 'ala Muhammad",
        translation: "O Allah, send blessings upon Muhammad",
        bengaliMeaning: "হে আল্লাহ! মুহাম্মদের উপর রহমত বর্ষণ করুন",
        virtue: "যে ব্যক্তি আমার উপর একবার দরুদ পাঠ করবে, আল্লাহ তার উপর দশবার রহমত বর্ষণ করবেন, তার দশটি গুনাহ মাফ করবেন এবং তার দশটি মর্যাদা বৃদ্ধি করবেন। (সুনানে নাসায়ী)",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 16,
        arabic: "ٱللَّٰهُمَّ ٱغْفِرْ لِي",
        transliteration: "Allahummaghfirli",
        translation: "O Allah, forgive me",
        bengaliMeaning: "হে আল্লাহ! আমাকে ক্ষমা করুন",
        virtue: "ক্ষমা প্রার্থনার মাধ্যমে আল্লাহর নৈকট্য লাভ করা যায়। রাসূল (সা.) প্রতিদিন ৭০ বারের বেশি আল্লাহর কাছে ক্ষমা চাইতেন। এই দোয়াটি নিজের গুনাহের জন্য অনুশোচনার একটি সহজ উপায়।",
        target: 100,
        category: "সাধারণ জিকির",
    },
    {
        id: 6,
        arabic: "آيَةُ الْكُرْسِيِّ",
        transliteration: "Ayatul Kursi",
        translation: "The Verse of the Throne",
        bengaliMeaning: "আয়াতুল কুরসি",
        virtue: "যে ব্যক্তি প্রতি ফরয নামাজের পর আয়াতুল কুরসি পাঠ করবে, তার এবং জান্নাতের মধ্যে কেবল মৃত্যুই বাধা থাকবে। (সুনানে নাসায়ী)",
        target: 1,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 7,
        arabic: "سُورَةُ الْإِخْلَاصِ",
        transliteration: "Surah Al-Ikhlas",
        translation: "The Sincerity",
        bengaliMeaning: "সূরা ইখলাস",
        virtue: "রাসূল (সা.) বলেছেন, 'সূরা ইখলাস কুরআনের এক-তৃতীয়াংশের সমান।' সকাল ও সন্ধ্যায় তিনবার পাঠ করলে তা সকল বিপদ থেকে রক্ষা করে।",
        target: 3,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 8,
        arabic: "سُورَةُ الْفَلَقِ",
        transliteration: "Surah Al-Falaq",
        translation: "The Daybreak",
        bengaliMeaning: "সূরা ফালাক",
        virtue: "সকাল ও সন্ধ্যায় তিনবার সূরা ফালাক পাঠ করলে যাবতীয় অনিষ্ট ও জাদু থেকে আল্লাহর আশ্রয় লাভ হয়।",
        target: 3,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 9,
        arabic: "سُورَةُ النَّاسِ",
        transliteration: "Surah An-Nas",
        translation: "The Mankind",
        bengaliMeaning: "সূরা নাস",
        virtue: "সকাল ও সন্ধ্যায় তিনবার সূরা নাস পাঠ করলে শয়তানের কুমন্ত্রণা ও মানুষের অনিষ্ট থেকে সুরক্ষা পাওয়া যায়।",
        target: 3,
        category: "সকাল-সন্ধ্যার জিকির",
    },
    {
        id: 10,
        arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
        transliteration: "Bismika Allahumma amutu wa ahya",
        translation: "In Your name, O Allah, I die and I live",
        bengaliMeaning: "হে আল্লাহ! আপনার নামেই আমি মৃত্যুবরণ করি এবং জীবিত হই",
        virtue: "রাসূলুল্লাহ (সা.) ঘুমানোর সময় এই দোয়াটি পড়তেন। এটি আল্লাহর হাতে নিজের জীবন ও মৃত্যু সঁপে দেওয়ার প্রতীক। (সহিহ বুখারি)",
        target: 1,
        category: "মাসনূন জিকির",
    },
    {
        id: 11,
        arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
        transliteration: "Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana Muslimin",
        translation: "Praise is to Allah Who has fed us and given us drink, and made us Muslims",
        bengaliMeaning: "সমস্ত প্রশংসা আল্লাহর জন্য, যিনি আমাদের খাইয়েছেন, পান করিয়েছেন এবং মুসলিমদের অন্তর্ভুক্ত করেছেন",
        virtue: "খাওয়ার পর এই দোয়া পাঠ করলে আল্লাহর প্রতি কৃতজ্ঞতা প্রকাশ করা হয় এবং তিনি নিয়ামত বাড়িয়ে দেন।",
        target: 1,
        category: "মাসনূন জিকির",
    },
    {
        id: 12,
        arabic: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ",
        transliteration: "Bismillahi, tawakkaltu 'alallah, la hawla wa la quwwata illa billah",
        translation: "In the name of Allah, I trust in Allah; there is no might and no power but in Allah",
        bengaliMeaning: "আল্লাহর নামে, আল্লাহর উপর ভরসা করলাম, আল্লাহ ছাড়া কোনো শক্তি বা ক্ষমতা নেই",
        virtue: "ঘর থেকে বের হওয়ার সময় এই দোয়া পাঠ করলে শয়তান থেকে সুরক্ষা পাওয়া যায় এবং আল্লাহ তার জন্য যথেষ্ট হয়ে যান। (সুনানে আবু দাউদ)",
        target: 1,
        category: "মাসনূন জিকির",
    }
];
